export type CategoryId =
  | "animals"
  | "food"
  | "toys"
  | "colors"
  | "body"
  | "family"
  | "us_presidents"
  | "modern_terms"
  | "world_basics"
  | "leadership"
  | "money"
  | "finance"
  | "space"
  | "universe"
  | "physics";

export type VocabItem = {
  id: string;
  word: string;
  imageQuery: string;
  emoji: string;
};

export type VocabCategory = {
  id: CategoryId;
  name: string;
  icon: string;
  description: string;
  items: VocabItem[];
};

const makeItems = (prefix: string, words: Array<{ word: string; query?: string; emoji?: string }>): VocabItem[] =>
  words.map(({ word, query, emoji }) => ({
    id: `${prefix}-${word.toLowerCase().replace(/\s+/g, "-")}`,
    word,
    imageQuery: query ?? word,
    emoji: emoji ?? "",
  }));

export const categories: VocabCategory[] = [
  {
    id: "animals",
    name: "Animals",
    icon: "🐶",
    description: "Friendly animals your child sees every day.",
    items: makeItems("animals", [
      { word: "Dog", query: "Dog", emoji: "🐕" },
      { word: "Cat", query: "Cat", emoji: "🐈" },
      { word: "Bird", query: "Bird", emoji: "🐦" },
      { word: "Fish", query: "Fish", emoji: "🐟" },
      { word: "Horse", query: "Horse", emoji: "🐴" },
      { word: "Cow", query: "Cattle", emoji: "🐄" },
      { word: "Rabbit", query: "Rabbit", emoji: "🐇" },
      { word: "Duck", query: "Duck", emoji: "🦆" },
      { word: "Elephant", query: "Elephant", emoji: "🐘" },
      { word: "Lion", query: "Lion", emoji: "🦁" },
      { word: "Tiger", query: "Tiger", emoji: "🐅" },
      { word: "Bear", query: "Bear", emoji: "🐻" },
      { word: "Penguin", query: "Penguin", emoji: "🐧" },
      { word: "Dolphin", query: "Dolphin", emoji: "🐬" },
      { word: "Butterfly", query: "Butterfly", emoji: "🦋" },
      { word: "Frog", query: "Frog", emoji: "🐸" },
      { word: "Turtle", query: "Turtle", emoji: "🐢" },
      { word: "Owl", query: "Owl", emoji: "🦉" },
      { word: "Sheep", query: "Sheep", emoji: "🐑" },
      { word: "Chicken", query: "Chicken", emoji: "🐔" },
    ]),
  },
  {
    id: "food",
    name: "Food",
    icon: "🍎",
    description: "Tasty food words for mealtime conversations.",
    items: makeItems("food", [
      { word: "Apple", query: "Apple", emoji: "🍎" },
      { word: "Banana", query: "Banana", emoji: "🍌" },
      { word: "Milk", query: "Milk", emoji: "🥛" },
      { word: "Bread", query: "Bread", emoji: "🍞" },
      { word: "Egg", query: "Egg (food)", emoji: "🥚" },
      { word: "Rice", query: "Rice", emoji: "🍚" },
      { word: "Cheese", query: "Cheese", emoji: "🧀" },
      { word: "Carrot", query: "Carrot", emoji: "🥕" },
      { word: "Strawberry", query: "Strawberry", emoji: "🍓" },
      { word: "Watermelon", query: "Watermelon", emoji: "🍉" },
      { word: "Pizza", query: "Pizza", emoji: "🍕" },
      { word: "Pasta", query: "Pasta", emoji: "🍝" },
      { word: "Soup", query: "Soup", emoji: "🍲" },
      { word: "Orange", query: "Orange (fruit)", emoji: "🍊" },
      { word: "Grape", query: "Grape", emoji: "🍇" },
      { word: "Corn", query: "Corn", emoji: "🌽" },
      { word: "Tomato", query: "Tomato", emoji: "🍅" },
      { word: "Potato", query: "Potato", emoji: "🥔" },
      { word: "Ice Cream", query: "Ice cream", emoji: "🍦" },
      { word: "Chocolate", query: "Chocolate", emoji: "🍫" },
    ]),
  },
  {
    id: "toys",
    name: "Toys",
    icon: "🧸",
    description: "Playtime objects children already love.",
    items: makeItems("toys", [
      { word: "Ball", query: "Ball", emoji: "⚽" },
      { word: "Blocks", query: "Toy block", emoji: "🧱" },
      { word: "Puzzle", query: "Jigsaw puzzle", emoji: "🧩" },
      { word: "Car", query: "Toy car", emoji: "🚗" },
      { word: "Doll", query: "Doll", emoji: "🪆" },
      { word: "Train", query: "Toy train", emoji: "🚂" },
      { word: "Book", query: "Picture book", emoji: "📚" },
      { word: "Drum", query: "Drum", emoji: "🥁" },
      { word: "Teddy Bear", query: "Teddy bear", emoji: "🧸" },
      { word: "Kite", query: "Kite", emoji: "🪁" },
      { word: "Yo-yo", query: "Yo-yo", emoji: "🪀" },
      { word: "Crayon", query: "Crayon", emoji: "🖍️" },
      { word: "Bicycle", query: "Bicycle", emoji: "🚲" },
      { word: "Swing", query: "Swing (seat)", emoji: "🎠" },
      { word: "Balloon", query: "Balloon", emoji: "🎈" },
      { word: "Skateboard", query: "Skateboard", emoji: "🛹" },
      { word: "Lego", query: "Lego", emoji: "🧱" },
      { word: "Robot", query: "Robot", emoji: "🤖" },
      { word: "Sandbox", query: "Sandbox", emoji: "🏖️" },
      { word: "Slide", query: "Playground slide", emoji: "🛝" },
    ]),
  },
  {
    id: "colors",
    name: "Colors",
    icon: "🌈",
    description: "Basic color names with visual examples.",
    items: makeItems("colors", [
      { word: "Red", query: "Red", emoji: "🔴" },
      { word: "Blue", query: "Blue", emoji: "🔵" },
      { word: "Green", query: "Green", emoji: "🟢" },
      { word: "Yellow", query: "Yellow", emoji: "🟡" },
      { word: "Orange", query: "Orange (colour)", emoji: "🟠" },
      { word: "Purple", query: "Purple", emoji: "🟣" },
      { word: "Pink", query: "Pink", emoji: "💗" },
      { word: "White", query: "White", emoji: "⚪" },
      { word: "Black", query: "Black", emoji: "⚫" },
      { word: "Brown", query: "Brown", emoji: "🟤" },
      { word: "Gold", query: "Gold (color)", emoji: "🥇" },
      { word: "Silver", query: "Silver (color)", emoji: "🥈" },
      { word: "Gray", query: "Grey", emoji: "🩶" },
      { word: "Cyan", query: "Cyan", emoji: "💠" },
      { word: "Magenta", query: "Magenta", emoji: "🩷" },
      { word: "Indigo", query: "Indigo", emoji: "💜" },
      { word: "Turquoise", query: "Turquoise (color)", emoji: "💎" },
      { word: "Maroon", query: "Maroon", emoji: "🟥" },
      { word: "Navy", query: "Navy blue", emoji: "🔷" },
      { word: "Beige", query: "Beige", emoji: "🤎" },
    ]),
  },
  {
    id: "body",
    name: "Body",
    icon: "🖐️",
    description: "Body part words toddlers can point to.",
    items: makeItems("body", [
      { word: "Eyes", query: "Human eye", emoji: "👁️" },
      { word: "Nose", query: "Human nose", emoji: "👃" },
      { word: "Mouth", query: "Human mouth", emoji: "👄" },
      { word: "Ear", query: "Ear", emoji: "👂" },
      { word: "Hand", query: "Hand", emoji: "🖐️" },
      { word: "Foot", query: "Foot", emoji: "🦶" },
      { word: "Hair", query: "Hair", emoji: "💇" },
      { word: "Teeth", query: "Human tooth", emoji: "🦷" },
      { word: "Arm", query: "Arm", emoji: "💪" },
      { word: "Leg", query: "Human leg", emoji: "🦵" },
      { word: "Finger", query: "Finger", emoji: "☝️" },
      { word: "Thumb", query: "Thumb", emoji: "👍" },
      { word: "Knee", query: "Knee", emoji: "🦵" },
      { word: "Elbow", query: "Elbow", emoji: "💪" },
      { word: "Shoulder", query: "Shoulder", emoji: "🙆" },
      { word: "Belly", query: "Abdomen", emoji: "🫃" },
      { word: "Back", query: "Human back", emoji: "🔙" },
      { word: "Neck", query: "Neck", emoji: "🦒" },
      { word: "Chin", query: "Chin", emoji: "😶" },
      { word: "Forehead", query: "Forehead", emoji: "🤦" },
    ]),
  },
  {
    id: "family",
    name: "Family",
    icon: "🏡",
    description: "Words for the people closest to them.",
    items: makeItems("family", [
      { word: "Mom", query: "Mother", emoji: "👩" },
      { word: "Dad", query: "Father", emoji: "👨" },
      { word: "Baby", query: "Infant", emoji: "👶" },
      { word: "Sister", query: "Sister", emoji: "👧" },
      { word: "Brother", query: "Brother", emoji: "👦" },
      { word: "Grandma", query: "Grandmother", emoji: "👵" },
      { word: "Grandpa", query: "Grandfather", emoji: "👴" },
      { word: "Friend", query: "Friendship", emoji: "🤝" },
      { word: "Uncle", query: "Uncle", emoji: "👨‍🦱" },
      { word: "Aunt", query: "Aunt", emoji: "👩‍🦱" },
      { word: "Cousin", query: "Cousin", emoji: "🧒" },
      { word: "Family", query: "Family", emoji: "👪" },
      { word: "Twin", query: "Twin", emoji: "👯" },
      { word: "Neighbor", query: "Neighbour", emoji: "🏘️" },
      { word: "Teacher", query: "Teacher", emoji: "👩‍🏫" },
      { word: "Doctor", query: "Physician", emoji: "👩‍⚕️" },
      { word: "Pet", query: "Pet", emoji: "🐾" },
      { word: "Home", query: "Home", emoji: "🏠" },
      { word: "Love", query: "Love", emoji: "❤️" },
      { word: "Hug", query: "Hug", emoji: "🤗" },
    ]),
  },
  {
    id: "us_presidents",
    name: "US Presidents",
    icon: "🇺🇸",
    description: "Early familiarity with important American leaders.",
    items: makeItems("us-presidents", [
      { word: "George Washington", emoji: "🏛️" },
      { word: "John Adams", emoji: "🏛️" },
      { word: "Thomas Jefferson", emoji: "🏛️" },
      { word: "James Madison", emoji: "🏛️" },
      { word: "Abraham Lincoln", emoji: "🎩" },
      { word: "Theodore Roosevelt", emoji: "🏛️" },
      { word: "Woodrow Wilson", emoji: "🏛️" },
      { word: "Franklin Roosevelt", query: "Franklin D. Roosevelt", emoji: "🏛️" },
      { word: "Harry Truman", query: "Harry S. Truman", emoji: "🏛️" },
      { word: "Dwight Eisenhower", query: "Dwight D. Eisenhower", emoji: "🏛️" },
      { word: "John Kennedy", query: "John F. Kennedy", emoji: "🏛️" },
      { word: "Richard Nixon", emoji: "🏛️" },
      { word: "Ronald Reagan", emoji: "🏛️" },
      { word: "George H.W. Bush", query: "George H. W. Bush", emoji: "🏛️" },
      { word: "Bill Clinton", emoji: "🏛️" },
      { word: "George W. Bush", emoji: "🏛️" },
      { word: "Barack Obama", emoji: "🏛️" },
      { word: "Donald Trump", emoji: "🏛️" },
      { word: "Joe Biden", emoji: "🏛️" },
      { word: "White House", query: "White House", emoji: "🏛️" },
    ]),
  },
  {
    id: "modern_terms",
    name: "Modern World",
    icon: "💡",
    description: "Big ideas children hear in the modern world.",
    items: makeItems("modern-terms", [
      { word: "Internet", query: "Internet", emoji: "🌐" },
      { word: "Robot", query: "Robot", emoji: "🤖" },
      { word: "Satellite", query: "Satellite", emoji: "🛰️" },
      { word: "Electric Car", query: "Electric car", emoji: "🚗" },
      { word: "Solar Panel", query: "Solar panel", emoji: "☀️" },
      { word: "Computer", query: "Personal computer", emoji: "💻" },
      { word: "Smartphone", query: "Smartphone", emoji: "📱" },
      { word: "Drone", query: "Unmanned aerial vehicle", emoji: "🛸" },
      { word: "3D Printer", query: "3D printing", emoji: "🖨️" },
      { word: "Virtual Reality", query: "Virtual reality", emoji: "🥽" },
      { word: "WiFi", query: "Wi-Fi", emoji: "📶" },
      { word: "GPS", query: "Global Positioning System", emoji: "📍" },
      { word: "Tablet", query: "Tablet computer", emoji: "📲" },
      { word: "Headphones", query: "Headphones", emoji: "🎧" },
      { word: "Camera", query: "Digital camera", emoji: "📷" },
      { word: "Battery", query: "Battery (electricity)", emoji: "🔋" },
      { word: "Wind Turbine", query: "Wind turbine", emoji: "🌬️" },
      { word: "Recycling", query: "Recycling", emoji: "♻️" },
      { word: "Microchip", query: "Integrated circuit", emoji: "🔬" },
      { word: "Space Suit", query: "Space suit", emoji: "🧑‍🚀" },
    ]),
  },
  {
    id: "world_basics",
    name: "World Basics",
    icon: "🌍",
    description: "Core global words for geography and culture.",
    items: makeItems("world-basics", [
      { word: "Earth", query: "Earth", emoji: "🌍" },
      { word: "Ocean", query: "Ocean", emoji: "🌊" },
      { word: "Mountain", query: "Mountain", emoji: "🏔️" },
      { word: "Continent", query: "Continent", emoji: "🗺️" },
      { word: "Map", query: "Map", emoji: "🗺️" },
      { word: "Flag", query: "Flag", emoji: "🏳️" },
      { word: "City", query: "City", emoji: "🏙️" },
      { word: "Country", query: "Country", emoji: "🌐" },
      { word: "River", query: "River", emoji: "🏞️" },
      { word: "Desert", query: "Desert", emoji: "🏜️" },
      { word: "Forest", query: "Forest", emoji: "🌲" },
      { word: "Island", query: "Island", emoji: "🏝️" },
      { word: "Volcano", query: "Volcano", emoji: "🌋" },
      { word: "Glacier", query: "Glacier", emoji: "🧊" },
      { word: "Waterfall", query: "Waterfall", emoji: "💧" },
      { word: "Canyon", query: "Canyon", emoji: "🏜️" },
      { word: "Lake", query: "Lake", emoji: "🏞️" },
      { word: "Cave", query: "Cave", emoji: "🕳️" },
      { word: "Jungle", query: "Jungle", emoji: "🌴" },
      { word: "Coral Reef", query: "Coral reef", emoji: "🪸" },
    ]),
  },
  {
    id: "leadership",
    name: "Leadership",
    icon: "👑",
    description: "Words that build confidence, character, and leadership.",
    items: makeItems("leadership", [
      { word: "Leader", query: "Leadership", emoji: "👑" },
      { word: "Courage", query: "Firefighter", emoji: "🦸" },
      { word: "Respect", query: "Handshake", emoji: "🤝" },
      { word: "Teamwork", query: "Teamwork", emoji: "🤜" },
      { word: "Kindness", query: "Kindness", emoji: "💖" },
      { word: "Honesty", query: "Honesty", emoji: "🫶" },
      { word: "Patience", query: "Patience", emoji: "🧘" },
      { word: "Bravery", query: "Medal of Honor", emoji: "🎖️" },
      { word: "Fairness", query: "Scales of justice", emoji: "⚖️" },
      { word: "Listening", query: "Active listening", emoji: "👂" },
      { word: "Sharing", query: "Sharing", emoji: "🤲" },
      { word: "Helping", query: "Volunteering", emoji: "🙋" },
      { word: "Promise", query: "Promise", emoji: "🤞" },
      { word: "Goal", query: "Goal setting", emoji: "🎯" },
      { word: "Dream", query: "Dream", emoji: "💭" },
      { word: "Confidence", query: "Confidence", emoji: "💪" },
      { word: "Focus", query: "Attention", emoji: "🔍" },
      { word: "Champion", query: "Champion", emoji: "🏆" },
      { word: "Hero", query: "Hero", emoji: "🦸‍♂️" },
      { word: "Victory", query: "Victory", emoji: "✌️" },
    ]),
  },
  {
    id: "money",
    name: "Money Basics",
    icon: "💵",
    description: "Early money words every child should recognize.",
    items: makeItems("money", [
      { word: "Coin", query: "Coin", emoji: "🪙" },
      { word: "Dollar", query: "United States dollar", emoji: "💵" },
      { word: "Wallet", query: "Wallet", emoji: "👛" },
      { word: "Piggy Bank", query: "Piggy bank", emoji: "🐷" },
      { word: "Cash", query: "Cash", emoji: "💰" },
      { word: "Price Tag", query: "Price tag", emoji: "🏷️" },
      { word: "Store", query: "Retail", emoji: "🏪" },
      { word: "Receipt", query: "Receipt", emoji: "🧾" },
      { word: "Penny", query: "Penny (United States coin)", emoji: "🪙" },
      { word: "Quarter", query: "Quarter (United States coin)", emoji: "🪙" },
      { word: "Credit Card", query: "Credit card", emoji: "💳" },
      { word: "ATM", query: "Automated teller machine", emoji: "🏧" },
      { word: "Change", query: "Coins", emoji: "🪙" },
      { word: "Shopping", query: "Shopping", emoji: "🛒" },
      { word: "Checkout", query: "Point of sale", emoji: "🏪" },
      { word: "Coupon", query: "Coupon", emoji: "🎫" },
      { word: "Tip", query: "Gratuity", emoji: "💸" },
      { word: "Bill", query: "Banknote", emoji: "💵" },
      { word: "Safe", query: "Safe (lock)", emoji: "🔐" },
      { word: "Gold", query: "Gold", emoji: "🥇" },
    ]),
  },
  {
    id: "finance",
    name: "Finance",
    icon: "📈",
    description: "Core finance concepts in child-friendly terms.",
    items: makeItems("finance", [
      { word: "Save", query: "Savings account", emoji: "🏦" },
      { word: "Spend", query: "Expenditure", emoji: "💸" },
      { word: "Budget", query: "Budget", emoji: "📋" },
      { word: "Bank", query: "Bank", emoji: "🏦" },
      { word: "Invest", query: "Investment", emoji: "📈" },
      { word: "Stock Market", query: "New York Stock Exchange", emoji: "📊" },
      { word: "Business", query: "Business", emoji: "💼" },
      { word: "Profit", query: "Profit (economics)", emoji: "💰" },
      { word: "Interest", query: "Interest", emoji: "📈" },
      { word: "Tax", query: "Tax", emoji: "🏛️" },
      { word: "Loan", query: "Loan", emoji: "🤝" },
      { word: "Wealth", query: "Wealth", emoji: "💎" },
      { word: "Insurance", query: "Insurance", emoji: "🛡️" },
      { word: "Trade", query: "Trade", emoji: "🔄" },
      { word: "Economy", query: "Economy", emoji: "🌐" },
      { word: "Dividend", query: "Dividend", emoji: "💵" },
      { word: "Currency", query: "Currency", emoji: "💱" },
      { word: "Debt", query: "Debt", emoji: "📉" },
      { word: "Market", query: "Market (economics)", emoji: "🏪" },
      { word: "Entrepreneur", query: "Entrepreneurship", emoji: "🚀" },
    ]),
  },
  {
    id: "space",
    name: "Space",
    icon: "🚀",
    description: "Exciting space words to spark big curiosity.",
    items: makeItems("space", [
      { word: "Rocket", query: "Rocket", emoji: "🚀" },
      { word: "Astronaut", query: "Astronaut", emoji: "🧑‍🚀" },
      { word: "Moon", query: "Moon", emoji: "🌙" },
      { word: "Mars", query: "Mars", emoji: "🔴" },
      { word: "Space Station", query: "International Space Station", emoji: "🛰️" },
      { word: "Telescope", query: "Telescope", emoji: "🔭" },
      { word: "Comet", query: "Comet", emoji: "☄️" },
      { word: "Galaxy", query: "Galaxy", emoji: "🌌" },
      { word: "Saturn", query: "Saturn", emoji: "🪐" },
      { word: "Jupiter", query: "Jupiter", emoji: "🪐" },
      { word: "Sun", query: "Sun", emoji: "☀️" },
      { word: "Meteor", query: "Meteoroid", emoji: "☄️" },
      { word: "Spacecraft", query: "Spacecraft", emoji: "🚀" },
      { word: "Space Shuttle", query: "Space Shuttle", emoji: "🚀" },
      { word: "Venus", query: "Venus", emoji: "🌟" },
      { word: "Mercury", query: "Mercury (planet)", emoji: "🌑" },
      { word: "Neptune", query: "Neptune", emoji: "🔵" },
      { word: "Uranus", query: "Uranus", emoji: "🔷" },
      { word: "Asteroid", query: "Asteroid", emoji: "🪨" },
      { word: "Constellation", query: "Constellation", emoji: "⭐" },
    ]),
  },
  {
    id: "universe",
    name: "Universe",
    icon: "🌌",
    description: "Big-picture cosmic ideas and objects.",
    items: makeItems("universe", [
      { word: "Universe", query: "Universe", emoji: "🌌" },
      { word: "Star", query: "Star", emoji: "⭐" },
      { word: "Planet", query: "Planet", emoji: "🪐" },
      { word: "Solar System", query: "Solar System", emoji: "☀️" },
      { word: "Milky Way", query: "Milky Way", emoji: "🌌" },
      { word: "Black Hole", query: "Black hole", emoji: "⚫" },
      { word: "Nebula", query: "Nebula", emoji: "🌈" },
      { word: "Orbit", query: "Orbit", emoji: "🔄" },
      { word: "Supernova", query: "Supernova", emoji: "💥" },
      { word: "Quasar", query: "Quasar", emoji: "💫" },
      { word: "Dark Matter", query: "Dark matter", emoji: "🔮" },
      { word: "Big Bang", query: "Big Bang", emoji: "💥" },
      { word: "Light Year", query: "Light-year", emoji: "✨" },
      { word: "Red Giant", query: "Red giant", emoji: "🔴" },
      { word: "White Dwarf", query: "White dwarf", emoji: "⚪" },
      { word: "Pulsar", query: "Pulsar", emoji: "💫" },
      { word: "Gravity Well", query: "Gravitational field", emoji: "🕳️" },
      { word: "Exoplanet", query: "Exoplanet", emoji: "🪐" },
      { word: "Cosmic Ray", query: "Cosmic ray", emoji: "⚡" },
      { word: "Andromeda", query: "Andromeda Galaxy", emoji: "🌌" },
    ]),
  },
  {
    id: "physics",
    name: "Physics",
    icon: "⚛️",
    description: "Foundational physics words for future problem-solvers.",
    items: makeItems("physics", [
      { word: "Force", query: "Force", emoji: "💪" },
      { word: "Energy", query: "Energy", emoji: "⚡" },
      { word: "Motion", query: "Motion (physics)", emoji: "🏃" },
      { word: "Gravity", query: "Gravity", emoji: "🍎" },
      { word: "Speed", query: "Speed", emoji: "💨" },
      { word: "Light", query: "Light", emoji: "💡" },
      { word: "Magnet", query: "Magnet", emoji: "🧲" },
      { word: "Atom", query: "Atom", emoji: "⚛️" },
      { word: "Electricity", query: "Electricity", emoji: "⚡" },
      { word: "Wave", query: "Wave", emoji: "🌊" },
      { word: "Friction", query: "Friction", emoji: "🤲" },
      { word: "Pressure", query: "Pressure", emoji: "🎈" },
      { word: "Temperature", query: "Temperature", emoji: "🌡️" },
      { word: "Sound", query: "Sound", emoji: "🔊" },
      { word: "Vibration", query: "Vibration", emoji: "〰️" },
      { word: "Momentum", query: "Momentum", emoji: "🏃‍♂️" },
      { word: "Lever", query: "Lever", emoji: "⚖️" },
      { word: "Pulley", query: "Pulley", emoji: "🔧" },
      { word: "Pendulum", query: "Pendulum", emoji: "🕰️" },
      { word: "Prism", query: "Prism (optics)", emoji: "🌈" },
    ]),
  },
];

export const categoriesById = categories.reduce<Record<CategoryId, VocabCategory>>(
  (acc, category) => {
    acc[category.id] = category;
    return acc;
  },
  {} as Record<CategoryId, VocabCategory>,
);
